version: '3'
services:
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile # Path to the .NET Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - frontend

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile # Path to the Angular Dockerfile
    ports:
      - "4200:80"  # Update the port mapping if needed
